### PR TITLE
suggested logo for Edam-Ontology

### PR DESCRIPTION
**Pull request by tawahpeggy**

### CODE REVIEW

**Review by matuskalas — CHANGES_REQUESTED** [review]
Million thanks @tawahpeggy, awesome!!! 🚀

Would you mind please renaming the file to something like "EDAM_logo_Peggy.svg" or so, just to make sure that people don't overwrite each other's work? And please add also the first version with the design for EDAM Browser, it was pretty, too! I'll merge it right after. Many thanks again! 👍🏽🙇🏽‍♂️

**Comment by tawahpeggy** [comment]
Thanks @matuskalas, will do as you've said

**Comment by tawahpeggy** [comment]
Hello @matuskalas,I have updated the PR as you stated, please check.

**Review by matuskalas — APPROVED** [review]
Awesomeee, thank you!!! 😸🙏🏽

**Comment by tawahpeggy** [comment]
Thanks

**Pull request merged**
