### PR TITLE
Adding my 2nd logo design

### PR DESCRIPTION
**Pull request by raashika03**
Description same as #3 
used same concept here too.

Took inspiration from these three places:-
[1st](https://www.123rf.com/photo_140346342_stock-vector-letter-e-with-dna-logo-or-symbol-template-design-vector.html)
[2nd](https://www.dreamstime.com/letter-e-dna-logo-symbol-template-design-vector-image172842704)
[3rd](https://www.shutterstock.com/image-vector/letter-e-dna-logo-symbol-template-1644791392)

At 3rd it's no where mentioned that one can't reuse it, so there shan't be copyright infringment right? @matuskalas I don't have so much idea about the same. I tried to google, but still don't have so much clarity on the same.

### CODE REVIEW

**Review by matuskalas — APPROVED** [review]
Nice! 🧬🚀
😸

**Comment by matuskalas** [comment]
With the not licensed stuff: It really is not available for reuse, so I'd suggest 2 things, in this order:
1. As a first aid, please add a smallprint note to the bottom of the logo, such as `Re-used work of © [Arif Nasrudin](https://www.dreamstime.com/dahlangraphic66_info). Fair use. Exempted from the CC BY-SA 4.0 license for this repository content.`
2. If you have a bit of time and feel like drawing some vector graphics, would you want to recreate your own version of the 🧬, ideally not too similar to the original?

**Comment by raashika03** [comment]
I'll go with the 2nd option. 
But I don't understand how come same image is there on three websites without copyright mention. 
So, I doubt if there'll be any copyright kind of thing.

**Comment by raashika03** [comment]
IMG_20210424_011000
@matuskalas on searching on Google by images. This comes as the result. As visually same images for #1 So does this also count as copyright infringement. I don't understand how much we can change to avoid this infringement thing.

**Comment by raashika03** [comment]
IMG_20210424_175134
@matuskalas I don't think change is needed. See this design is also similar just that small circle is not present. So what I proposed can't be said to be same as the original one. 

This also
IMG_20210424_180049

**Pull request merged**
