### PR TITLE
Suggested logos for Edam Browser

### PR DESCRIPTION
**Pull request by Chiamaka-Uzuegbu**
I created two logos for the Edam Ontology and also created a documentation which elucidates on the importance of logos to a brand.

### CODE REVIEW

**Review by matuskalas — APPROVED** [review]
Awesome, million thanks @Chiamaka-Uzuegbu! 🙏🏽😸

Is this all your work from scratch, or have you used any bits of some other people's designs? (asking just because of license)

**Comment by Chiamaka-Uzuegbu** [comment]
@matuskalas Oh, thank you so much. Yes, it is all from scratch. I used a tool online, so if this is what you mean by using other peoples design, then I probably did. But it was from scratch.

**Comment by matuskalas** [comment]
Thank you so much for your prompt clarification, that's super awesome!

Clarification from my side: Using someone's tool normally does NOT mean using someone else's design in yours, unless the license or terms of use of that tool would indicate otherwise (that would however only really make sense if the tool includes some pre-made designs, patterns, templates, _etc._). "From scratch" is normally understood as not building upon someone else's work👍🏽

**Comment by Chiamaka-Uzuegbu** [comment]
Okay thank you for the clarification.

**Pull request merged**
